# Generated by Django 3.2.9 on 2021-11-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwsInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cpu', models.IntegerField()),
                ('Memory_GB', models.IntegerField()),
                ('AWS_Instance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DB_Type', models.CharField(max_length=50)),
                ('Application', models.CharField(blank=True, max_length=200)),
                ('AWS_Services', models.CharField(max_length=100)),
            ],
        ),
    ]
