# Generated by Django 3.2.9 on 2021-11-21 20:59

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('EmpId', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField(blank=True)),
                ('Team', models.CharField(blank=True, max_length=30)),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=254)),
                ('Email', models.EmailField(max_length=60, unique=True, validators=[user.models.WhitelistEmailValidator(whitelist=['tsys.com', 'globalpay.com'])])),
                ('Creation_Date', models.DateField(auto_now_add=True)),
                ('Last_Modified_Date', models.DateField(auto_now=True)),
            ],
        ),
    ]
