# Generated by Django 3.2.9 on 2021-11-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='EmpId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='Password',
            field=models.BinaryField(max_length=254),
        ),
    ]
