# Generated by Django 3.2.9 on 2021-11-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211123_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='Password',
            field=models.TextField(max_length=254),
        ),
    ]
