# Generated by Django 3.2.9 on 2021-11-27 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_directory_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='DOB',
        ),
    ]
